version: '2'
services:
    productservice-app:
        image: productservice
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://productservice-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=ProductService
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    productservice-mongodb:
        extends:
            file: mongodb.yml
            service: productservice-mongodb
